import { neon } from '@neondatabase/serverless';
import { parse } from 'dotenv';
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  mkdtempSync,
  symlinkSync,
  copyFileSync,
} from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';

const backend = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const root = resolve(backend, '..');
const directory = resolve(root, 'docs/phase16-validation');
mkdirSync(directory, { recursive: true });
const config = {
  ...parse(readFileSync(resolve(root, '.env'))),
  ...process.env,
};
const target = config.TEST_DATABASE_URL;
const url = new URL(target);
if (
  url.hostname !==
    'ep-royal-star-b253pvlk-pooler.c-6.eu-central-1.aws.neon.tech' ||
  url.pathname !== '/neondb'
)
  throw new Error(
    'STOP: test endpoint differs from authorized disposable branch',
  );
const sql = neon(target);
async function verifyIdentity() {
  const [identity] = await sql.query(
    "SELECT current_database() AS database, current_setting('neon.branch_id') AS branch, current_setting('neon.endpoint_id') AS endpoint",
  );
  if (
    identity.database !== 'neondb' ||
    identity.branch !== 'br-misty-moon-b2be9vmt' ||
    identity.endpoint !== 'ep-royal-star-b253pvlk'
  )
    throw new Error('STOP: disposable database identity mismatch');
  return identity;
}
const identity = await verifyIdentity();
const mode = process.argv[2];
if (mode === 'cleanup-probe') {
  const responses = readFileSync(
    join(directory, 'contracts-corrected-http.jsonl'),
    'utf8',
  )
    .trim()
    .split('\n')
    .map((line) => JSON.parse(line));
  const ids = [
    ...new Set(responses.map((row) => row.body?.competitionId).filter(Boolean)),
  ];
  if (ids.length !== 1)
    throw new Error('Expected one competition from this probe evidence');
  const teams = await sql.query(
    'SELECT t.id, t.name, tm.user_id FROM competition_teams ct JOIN teams t ON t.id = ct.team_id JOIN team_members tm ON tm.team_id = t.id WHERE ct.competition_id = $1',
    [ids[0]],
  );
  if (
    teams.length !== 2 ||
    teams.some((t) => !/^phase16-[cd] Test Team /.test(t.name))
  )
    throw new Error('STOP: cleanup does not match exact synthetic probe teams');
  await sql.query('DELETE FROM matches WHERE competition_id = $1', [ids[0]]);
  for (const team of teams)
    await sql.query('DELETE FROM teams WHERE id = $1', [team.id]);
  for (const team of teams)
    await sql.query('DELETE FROM "user" WHERE id = $1', [team.user_id]);
  await verifyIdentity();
  writeFileSync(
    join(directory, 'cleanup-probe.json'),
    JSON.stringify(
      {
        identity,
        competitionId: ids[0],
        teams,
        completed: true,
        scope:
          'Only identities/teams/sheets generated by contracts-corrected probe',
      },
      null,
      2,
    ),
  );
  console.log(
    'Cleaned only the retained synthetic diagnostic fixture identities after removing their sheets.',
  );
  process.exit(0);
}
if (
  ![
    'base',
    'base-corrected',
    'current',
    'affected',
    'final',
    'contracts',
    'contracts-corrected',
    'contracts-final',
    'cleanup-probe',
    'unit',
    'integrity',
    'build',
    'lint',
  ].includes(mode)
)
  throw new Error(
    'Expected base/base-corrected/current/affected/final/contracts',
  );
const temporary = mkdtempSync(join(tmpdir(), 'sport-phase16-'));
let cwd = backend;
function checked(command, args) {
  const result = spawnSync(command, args, {
    cwd: root,
    encoding: 'utf8',
    windowsHide: true,
  });
  if (result.error || result.status !== 0)
    throw new Error(
      `Process failure: ${command}: ${result.error ?? result.stderr}`,
    );
  return result.stdout.trim();
}
if (mode.startsWith('base')) {
  const archive = join(temporary, 'base.tar');
  checked('git', [
    'archive',
    '--format=tar',
    '--output',
    archive,
    'e01fe3d18be0c47edc8a56ebcd70d7d83c9a7dec',
  ]);
  const checkout = join(temporary, 'base');
  mkdirSync(checkout);
  checked('tar', ['-xf', archive, '-C', checkout]);
  cwd = join(checkout, 'backend');
  symlinkSync(
    join(backend, 'node_modules'),
    join(cwd, 'node_modules'),
    'junction',
  );
  if (mode === 'base-corrected')
    copyFileSync(
      join(backend, 'test/friendly-fixtures.e2e-spec.ts'),
      join(cwd, 'test/friendly-fixtures.e2e-spec.ts'),
    );
}
// Observe real responses without altering any assertions or application code.
const hook = join(temporary, 'capture.cjs');
writeFileSync(
  hook,
  `const fs = require('node:fs');
const Test = require(${JSON.stringify(join(backend, 'node_modules/supertest/lib/test.js'))});
const original = Test.prototype.end;
Test.prototype.end = function (callback) {
  const test = this;
  return original.call(this, function (error, response) {
    if (response && test.method === 'GET' && /\\/(?:friendly-opponent-lineup|opponent-lineup|lineup)$|\\/matches\\/[a-f0-9-]+$/.test(new URL(test.url).pathname)) {
      fs.appendFileSync(process.env.PHASE16_HTTP_FILE, JSON.stringify({test: expect.getState().currentTestName, method: test.method, endpoint: new URL(test.url).pathname, flag: process.env.TWO_SIDED_LIVE_LOGGING_ENABLED, status: response.status, body: response.body, text: response.text}) + '\\n');
    }
    callback(error, response);
  });
};
`,
);
const evidence = join(directory, `${mode}-http.jsonl`);
writeFileSync(evidence, '');
let args = [
  join(backend, 'node_modules/jest/bin/jest.js'),
  '--config',
  './test/jest-e2e.json',
  '--runInBand',
  mode.startsWith('contracts')
    ? 'test/phase16-lineup-contract.e2e-spec.ts'
    : 'test/friendly-fixtures.e2e-spec.ts',
  '--setupFilesAfterEnv',
  hook,
  '--json',
  '--outputFile',
  join(directory, `${mode}-jest.json`),
];
if (mode === 'unit' || mode === 'integrity') {
  args = [join(backend, 'node_modules/jest/bin/jest.js'), '--runInBand'];
  if (mode === 'integrity')
    args.push('src/matches/shared-session-integrity.spec.ts');
  args.unshift('--experimental-vm-modules'); // Required by the repository unit script.
} else if (mode === 'build') {
  args = [join(backend, 'node_modules/@nestjs/cli/bin/nest.js'), 'build'];
} else if (mode === 'lint') {
  args = [
    join(backend, 'node_modules/eslint/bin/eslint.js'),
    'test/friendly-fixtures.e2e-spec.ts',
    'test/phase16-lineup-contract.e2e-spec.ts',
  ];
}
if (['base', 'base-corrected', 'current', 'affected'].includes(mode))
  args.push(
    '--testNamePattern',
    'keeps the opponent lineup unavailable|shares the opponent.s confirmed lineup|never falls back to a different match|shares each confirmed pre-kickoff lineup',
  );
const env = {
  ...config,
  TEST_DATABASE_URL: target,
  TWO_SIDED_LIVE_LOGGING_ENABLED: 'true',
  OFFLINE_SYNC_ENABLED: 'true',
  BREVO_API_KEY: '',
  PHASE16_HTTP_FILE: evidence,
};
const started = Date.now();
let output = '';
const child = spawn(process.execPath, args, { cwd, env, windowsHide: true });
for (const stream of [child.stdout, child.stderr])
  stream.on('data', (chunk) => {
    output += chunk;
    process.stdout.write(chunk);
  });
const code = await new Promise((accept, reject) => {
  child.on('error', reject);
  child.on('close', accept);
});
await verifyIdentity();
writeFileSync(join(directory, `${mode}.log`), output);
writeFileSync(
  join(directory, `${mode}-process.json`),
  JSON.stringify(
    {
      identity,
      mode,
      sourceSha: mode.startsWith('base')
        ? 'e01fe3d18be0c47edc8a56ebcd70d7d83c9a7dec'
        : checked('git', ['rev-parse', 'HEAD']),
      correctedAssertions: ['base-corrected', 'affected', 'final'].includes(
        mode,
      ),
      command: [process.execPath, ...args],
      cwd,
      exitCode: code,
      durationSeconds: (Date.now() - started) / 1000,
      schema:
        'Existing migrated disposable branch including 0052; no migration or schema reset performed',
    },
    null,
    2,
  ),
);
process.exitCode = code;
