/**
 * Exports the current game plan — the formation on the pitch plus the
 * tactical settings — as a printable PDF a coach can bring to training or a
 * match: a "Main XI" page (pitch diagram + substitutes) followed by a
 * dedicated "Tactics" page (defence/offence cards + set-piece roles).
 *
 * Built with jsPDF's vector drawing primitives rather than a DOM screenshot
 * (e.g. html2canvas): the pitch positions are already known as percentage
 * coordinates (see `Formation`), so drawing them directly gives a crisp
 * result at any zoom/print size and never depends on capturing the app's
 * live CSS correctly. Tactics get their own page rather than being packed
 * under the pitch — that's fixed real estate, not overflow room, so nothing
 * gets silently clipped off the bottom of the sheet as the squad grows.
 */

import jsPDF, { GState } from "jspdf";
import type { BackendAthlete } from "@/services/athletes";
import type { GamePlanTactics } from "@/services/gamePlans";
import type {
  Formation,
  PitchAssignments,
} from "@/features/team-management/types";
import {
  DEFENSIVE_STYLE_OPTIONS,
  OFFENSIVE_STYLE_OPTIONS,
  defensiveStyleDescription,
  type StyleOption,
} from "./tactics-options";

export interface GamePlanExportData {
  /** Saved plan name, or a fallback when the board hasn't been saved yet. */
  planName: string;
  teamName: string | null;
  /** Team brand color (hex, e.g. "#00D99A"); falls back to navy when unset. */
  teamColor: string | null;
  formation: Formation;
  assignments: PitchAssignments;
  substituteIds: string[];
  tactics: GamePlanTactics;
  getAthlete: (athleteId: string | null) => BackendAthlete | null;
}

/* ─── Palette & layout constants ─────────────────────────────────────── */

type Rgb = [number, number, number];

const PAGE_MARGIN = 40;
const DEFAULT_ACCENT: Rgb = [30, 58, 95]; // navy — used when no team color is set
const GK_MARKER: Rgb = [217, 119, 6]; // amber — goalkeeper always stands out
const PITCH_STRIPE_A: Rgb = [33, 110, 62];
const PITCH_STRIPE_B: Rgb = [39, 122, 69];
const TEXT_DARK: Rgb = [23, 23, 23];
const TEXT_MUTED: Rgb = [110, 110, 116];
const CARD_BG: Rgb = [247, 247, 249];
const CARD_BORDER: Rgb = [224, 225, 229];
const TRACK_BG: Rgb = [222, 224, 228];

/** Parses "#rgb" or "#rrggbb" into 0–255 channels; null on anything else. */
function hexToRgb(hex: string | null): Rgb | null {
  if (!hex) return null;
  const match = /^#?([a-f\d]{3}|[a-f\d]{6})$/i.exec(hex.trim());
  if (!match) return null;
  let value = match[1];
  if (value.length === 3) {
    value = value
      .split("")
      .map((c) => c + c)
      .join("");
  }
  const num = parseInt(value, 16);
  return [(num >> 16) & 255, (num >> 8) & 255, num & 255];
}

/** Picks black or white text for legibility against `bg` (WCAG-ish luminance). */
function contrastOn([r, g, b]: Rgb): Rgb {
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.6 ? [23, 23, 23] : [255, 255, 255];
}

function athleteLabel(athlete: BackendAthlete | null): string {
  if (!athlete) return "Unassigned";
  const number = athlete.squadNumber != null ? `${athlete.squadNumber}. ` : "";
  return `${number}${athlete.firstName} ${athlete.lastName}`.trim();
}

function styleLabel<T extends string>(
  options: StyleOption<T>[],
  value: T,
): string {
  return options.find((option) => option.value === value)?.label ?? value;
}

/* ─── Shared chrome: header + footer ─────────────────────────────────── */

function drawPageHeader(
  doc: jsPDF,
  contentWidth: number,
  accent: Rgb,
  title: string,
  subtitle: string,
): number {
  let y = PAGE_MARGIN;

  // Brand accent bar across the top of every page.
  doc.setFillColor(...accent);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...TEXT_DARK);
  doc.text(title, PAGE_MARGIN, y);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(subtitle, PAGE_MARGIN, y);
  doc.text(new Date().toLocaleDateString(), PAGE_MARGIN + contentWidth, y, {
    align: "right",
  });
  y += 10;

  doc.setDrawColor(...CARD_BORDER);
  doc.setLineWidth(1);
  doc.line(PAGE_MARGIN, y, PAGE_MARGIN + contentWidth, y);

  return y + 20;
}

function drawFooters(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text("Generated by Gaffer", PAGE_MARGIN, pageHeight - 20);
    doc.text(
      `Page ${page} of ${pageCount}`,
      pageWidth - PAGE_MARGIN,
      pageHeight - 20,
      { align: "right" },
    );
  }
}

/* ─── Page 1: pitch + substitutes ────────────────────────────────────── */

function drawPitch(
  doc: jsPDF,
  data: GamePlanExportData,
  contentWidth: number,
  top: number,
  accent: Rgb,
): number {
  const pitchWidth = Math.min(340, contentWidth);
  const pitchHeight = pitchWidth * 1.4;
  const pitchLeft = PAGE_MARGIN + (contentWidth - pitchWidth) / 2;

  // Mown-grass stripes, clipped to the pitch rect.
  const stripeCount = 9;
  const stripeHeight = pitchHeight / stripeCount;
  for (let i = 0; i < stripeCount; i += 1) {
    doc.setFillColor(...(i % 2 === 0 ? PITCH_STRIPE_A : PITCH_STRIPE_B));
    doc.rect(pitchLeft, top + i * stripeHeight, pitchWidth, stripeHeight, "F");
  }

  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(1.2);
  doc.rect(pitchLeft + 6, top + 6, pitchWidth - 12, pitchHeight - 12, "S");
  doc.line(
    pitchLeft + 6,
    top + pitchHeight / 2,
    pitchLeft + pitchWidth - 6,
    top + pitchHeight / 2,
  );
  doc.circle(pitchLeft + pitchWidth / 2, top + pitchHeight / 2, pitchWidth * 0.14, "S");
  doc.setFillColor(255, 255, 255);
  doc.circle(pitchLeft + pitchWidth / 2, top + pitchHeight / 2, 1.4, "F");

  // Penalty + six-yard boxes at both ends, for a recognisable pitch outline.
  const penaltyWidth = pitchWidth * 0.62;
  const penaltyHeight = pitchHeight * 0.14;
  const sixYardWidth = pitchWidth * 0.32;
  const sixYardHeight = pitchHeight * 0.055;
  const penaltyLeft = pitchLeft + (pitchWidth - penaltyWidth) / 2;
  const sixYardLeft = pitchLeft + (pitchWidth - sixYardWidth) / 2;
  for (const fromTop of [true, false]) {
    const penaltyY = fromTop ? top + 6 : top + pitchHeight - 6 - penaltyHeight;
    const sixYardY = fromTop ? top + 6 : top + pitchHeight - 6 - sixYardHeight;
    doc.rect(penaltyLeft, penaltyY, penaltyWidth, penaltyHeight, "S");
    doc.rect(sixYardLeft, sixYardY, sixYardWidth, sixYardHeight, "S");
  }

  // Player markers: goalkeeper always amber, outfield players in the team's
  // brand color, each labeled with a squad number and a legible name chip.
  for (const position of data.formation.positions) {
    const cx = pitchLeft + (position.x / 100) * pitchWidth;
    const cy = top + (position.y / 100) * pitchHeight;
    const athlete = data.getAthlete(data.assignments[position.id] ?? null);
    const markerColor = position.role === "GK" ? GK_MARKER : accent;
    const markerText = contrastOn(markerColor);

    doc.setFillColor(...markerColor);
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(1);
    doc.circle(cx, cy, 13, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...markerText);
    doc.text(position.label, cx, cy + 2.8, { align: "center" });

    const label = athleteLabel(athlete);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    const maxWidth = 66;
    const lines = doc.splitTextToSize(label, maxWidth) as string[];
    const lineHeight = 8;
    const chipWidth =
      Math.min(
        maxWidth,
        Math.max(...lines.map((line) => doc.getTextWidth(line))),
      ) + 8;
    const chipHeight = lines.length * lineHeight + 4;
    const chipTop = cy + 17;

    doc.setGState(new GState({ opacity: 0.4 }));
    doc.setFillColor(10, 10, 10);
    doc.roundedRect(
      cx - chipWidth / 2,
      chipTop,
      chipWidth,
      chipHeight,
      2,
      2,
      "F",
    );
    doc.setGState(new GState({ opacity: 1 }));

    doc.setTextColor(255, 255, 255);
    lines.forEach((line, i) => {
      doc.text(line, cx, chipTop + 8 + i * lineHeight, { align: "center" });
    });
  }

  doc.setTextColor(...TEXT_DARK);
  return top + pitchHeight + 24;
}

function drawSubstitutes(
  doc: jsPDF,
  data: GamePlanExportData,
  contentWidth: number,
  top: number,
): number {
  let y = top;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_DARK);
  doc.text("SUBSTITUTES", PAGE_MARGIN, y);
  y += 16;

  if (data.substituteIds.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...TEXT_MUTED);
    doc.text("None named", PAGE_MARGIN, y);
    return y + 16;
  }

  // A tidy multi-column grid instead of one long wrapped line.
  const columns = data.substituteIds.length > 6 ? 3 : 2;
  const columnWidth = contentWidth / columns;
  const rowHeight = 15;
  const perColumn = Math.ceil(data.substituteIds.length / columns);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...TEXT_DARK);
  data.substituteIds.forEach((id, index) => {
    const column = Math.floor(index / perColumn);
    const row = index % perColumn;
    doc.text(
      athleteLabel(data.getAthlete(id)),
      PAGE_MARGIN + column * columnWidth,
      y + row * rowHeight,
    );
  });

  return y + perColumn * rowHeight + 8;
}

/* ─── Page 2: tactics ─────────────────────────────────────────────────── */

/** Draws a rounded card shell and its uppercase title; returns the y content
 * should start at inside the card. */
function drawCard(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  title: string,
  accent: Rgb,
): number {
  doc.setFillColor(...CARD_BG);
  doc.setDrawColor(...CARD_BORDER);
  doc.setLineWidth(1);
  doc.roundedRect(x, y, width, height, 8, 8, "FD");

  doc.setFillColor(...accent);
  doc.rect(x, y, 4, height, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(title.toUpperCase(), x + 18, y + 20);

  return y + 40;
}

/** A bold label with its value right-aligned within the card. */
function drawLabelValueRow(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  label: string,
  value: string,
): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(label, x + 18, y);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEXT_DARK);
  doc.text(value, x + width - 18, y, { align: "right" });

  return y + 20;
}

/** A label above a filled progress track — used for the 0–10 tactic sliders. */
function drawSliderRow(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  label: string,
  value: number,
  max: number,
  accent: Rgb,
): number {
  const trackX = x + 18;
  const trackWidth = width - 36;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(label, trackX, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEXT_DARK);
  doc.text(`${value}/${max}`, x + width - 18, y, { align: "right" });

  const trackY = y + 6;
  doc.setFillColor(...TRACK_BG);
  doc.roundedRect(trackX, trackY, trackWidth, 5, 2.5, 2.5, "F");
  const filled = Math.max(6, (value / max) * trackWidth);
  doc.setFillColor(...accent);
  doc.roundedRect(trackX, trackY, filled, 5, 2.5, 2.5, "F");

  return y + 26;
}

/** Small muted, wrapped trade-off note — mirrors the copy shown under the
 * style picker in the app's own Tactics tab. */
function drawNote(doc: jsPDF, x: number, y: number, width: number, text: string): void {
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED);
  const lines = doc.splitTextToSize(text, width - 36) as string[];
  doc.text(lines, x + 18, y);
}

function drawTacticsPage(
  doc: jsPDF,
  data: GamePlanExportData,
  contentWidth: number,
  top: number,
  accent: Rgb,
): void {
  const gap = 16;
  const columnWidth = (contentWidth - gap) / 2;
  const cardHeight = 190;

  let y = drawCard(
    doc,
    PAGE_MARGIN,
    top,
    columnWidth,
    cardHeight,
    "Defence",
    accent,
  );
  y = drawLabelValueRow(
    doc,
    PAGE_MARGIN,
    y,
    columnWidth,
    "Defensive style",
    styleLabel(DEFENSIVE_STYLE_OPTIONS, data.tactics.defensiveStyle),
  );
  y = drawSliderRow(
    doc,
    PAGE_MARGIN,
    y + 6,
    columnWidth,
    "Width",
    data.tactics.defensiveWidth,
    10,
    accent,
  );
  y = drawSliderRow(
    doc,
    PAGE_MARGIN,
    y + 6,
    columnWidth,
    "Depth",
    data.tactics.defensiveDepth,
    10,
    accent,
  );
  drawNote(
    doc,
    PAGE_MARGIN,
    y + 16,
    columnWidth,
    defensiveStyleDescription(data.tactics.defensiveStyle),
  );

  const rightX = PAGE_MARGIN + columnWidth + gap;
  let ry = drawCard(
    doc,
    rightX,
    top,
    columnWidth,
    cardHeight,
    "Offence",
    accent,
  );
  ry = drawLabelValueRow(
    doc,
    rightX,
    ry,
    columnWidth,
    "Offensive style",
    styleLabel(OFFENSIVE_STYLE_OPTIONS, data.tactics.offensiveStyle),
  );
  ry = drawSliderRow(
    doc,
    rightX,
    ry + 6,
    columnWidth,
    "Width",
    data.tactics.offensiveWidth,
    10,
    accent,
  );
  ry = drawSliderRow(
    doc,
    rightX,
    ry + 6,
    columnWidth,
    "Players in box",
    data.tactics.playersInBox,
    10,
    accent,
  );
  ry = drawSliderRow(
    doc,
    rightX,
    ry + 6,
    columnWidth,
    "Corners commitment",
    data.tactics.cornersCommitment,
    10,
    accent,
  );
  drawSliderRow(
    doc,
    rightX,
    ry + 6,
    columnWidth,
    "Free kicks commitment",
    data.tactics.freeKicksCommitment,
    10,
    accent,
  );

  // Set-piece roles: one full-width card, laid out as a 2x2 grid.
  const rolesTop = top + cardHeight + gap;
  const rolesHeight = 130;
  const rolesContentTop = drawCard(
    doc,
    PAGE_MARGIN,
    rolesTop,
    contentWidth,
    rolesHeight,
    "Set-piece roles",
    accent,
  );
  const roleColumnWidth = contentWidth / 2;
  const roles: [string, string | null][] = [
    ["Captain", data.tactics.captainId],
    ["Free kick taker", data.tactics.freeKickTakerId],
    ["Penalty taker", data.tactics.penaltyTakerId],
    ["Corner taker", data.tactics.cornerTakerId],
  ];
  roles.forEach(([label, athleteId], index) => {
    const column = index % 2;
    const row = Math.floor(index / 2);
    const x = PAGE_MARGIN + column * roleColumnWidth;
    const y = rolesContentTop + row * 34;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(label.toUpperCase(), x + 18, y);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(...TEXT_DARK);
    doc.text(athleteLabel(data.getAthlete(athleteId)), x + 18, y + 14);
  });
}

/* ─── Entry points ────────────────────────────────────────────────────── */

/** Builds the plan's PDF document without triggering a download — used by
 * `downloadGamePlanPdf` and available directly for tests. */
export function buildGamePlanPdf(data: GamePlanExportData): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const contentWidth = doc.internal.pageSize.getWidth() - PAGE_MARGIN * 2;
  const accent = hexToRgb(data.teamColor) ?? DEFAULT_ACCENT;
  const subtitle = [data.teamName, data.formation.name]
    .filter((part): part is string => Boolean(part))
    .join("  ·  ");

  let y = drawPageHeader(doc, contentWidth, accent, data.planName, subtitle);
  y = drawPitch(doc, data, contentWidth, y, accent);
  drawSubstitutes(doc, data, contentWidth, y);

  doc.addPage();
  const tacticsTop = drawPageHeader(doc, contentWidth, accent, "Tactics", subtitle);
  drawTacticsPage(doc, data, contentWidth, tacticsTop, accent);

  drawFooters(doc);

  return doc;
}

/** Turns a plan name into a safe, lowercase, hyphenated filename stem. */
export function slugifyFileName(name: string): string {
  const slug = name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-+|-+$)/g, "");
  return slug || "game-plan";
}

/** Builds the plan's PDF and triggers a browser download of it. */
export function downloadGamePlanPdf(data: GamePlanExportData): void {
  const doc = buildGamePlanPdf(data);
  doc.save(`${slugifyFileName(data.planName)}.pdf`);
}
